# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(default=None, max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(default=None, max_length=200, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
