# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20171117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[^ ]+')]),
        ),
    ]
