# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_auto_20171102_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
