# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_auto_20171107_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
